# update all the pre-commit hooks - `pre-commit autoupdate`
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: [--enforce-all, --maxkb=70000] # 70mb
        require_serial: true

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
  # - repo: https://github.com/astral-sh/uv-pre-commit
  #   # To make sure your uv.lock file is up to date even if your pyproject.toml file was changed
  #   rev: 0.8.0
  #   hooks:
  #     - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/PyCQA/bandit
    # find common security issues in python code
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-s", "B101"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --skip=logs/**,data/**,*.ipynb, examples/**
          - --ignore-words-list=abc,def,fpr,tpr,roc_auc,auc
