[project]
name = "yoga-pose-estimation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.11.0.86",
    "ultralytics>=8.3.189",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
